version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local
    ports:
      - "3306:3306"
  goose:
    build: .
    container_name: goose
    command: ""
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
